#!/usr/bin/python3

# GoldenDict History Enhancer

import random, json, os, sys

file_dir = os.path.dirname(__file__)
WORD_LIST_DIR = os.path.join(file_dir, 'voclist.txt')
DAILY_WORDS_DIR = os.path.join(file_dir, 'daily_words.json')
TEMP_HISTORY_DIR = os.path.join(file_dir, 'history')
INDEX_DIR = os.path.join(file_dir, 'index.json')
N = 24

def generate_daily_word_list():
    with open(WORD_LIST_DIR) as f:
        lines = f.readlines()
        lines = [line.rstrip('\n') for line in lines]

    word_count = len(lines)
    random.shuffle(lines)

    daily_lens = [N for _ in range(word_count // N)]
    daily_lens.append(len(lines) - len(daily_lens) * N)

    daily_words = [lines[day * N: day * N + daily_len] for day, daily_len in enumerate(daily_lens)]

    with open(DAILY_WORDS_DIR, 'w') as f:
        json.dump(daily_words, f)

def current_history():
    os.system(f'cp ~/.goldendict/history {TEMP_HISTORY_DIR}')
    with open(TEMP_HISTORY_DIR) as f:
        lines = f.readlines()
    os.system(f'rm {TEMP_HISTORY_DIR}')
    return lines

def add_word_list(index):
    with open(DAILY_WORDS_DIR) as f:
        daily_words = json.load(f)
    
    today_words = daily_words[index]
    print("Current index: {}. Total: {}.".format(index, len(daily_words)))

    today_list = ['1 {}\n'.format(word) for word in today_words]

    history = current_history()
    for word in today_list:
        if word not in history:
            history.insert(0, word)

    os.system('killall goldendict')
    os.system('cp ~/.goldendict/history ~/.goldendict/history.bak')
    with open(TEMP_HISTORY_DIR, 'w') as f:
        f.writelines(history)
    
    os.system(f'mv {TEMP_HISTORY_DIR} ~/.goldendict/history')
            

def update():
    with open(INDEX_DIR, 'r') as f:
        index = json.load(f)
    
    with open(INDEX_DIR, 'w') as f:
        index += 1
        add_word_list(index)
        json.dump(index, f)

def undo():
    os.system('killall goldendict')
    os.system('mv ~/.goldendict/history.bak ~/.goldendict/history')
    with open(INDEX_DIR, 'r') as f:
        index = json.load(f)
    with open(INDEX_DIR, 'w') as f:
        index -= 1
        json.dump(index, f)


if __name__ == '__main__':
    if os.path.exists(DAILY_WORDS_DIR) == False:
        s = input('Initialize? [Y/N] ')
        if s in 'Yy':
            generate_daily_word_list()
        else:
            print('Must Init before using this program!')
            sys.exit(1)
        
    s = input("Update GoldenDict history list? [Y/N] ")
    if s in 'Yy':
        update()
        print("Done!")
    if s in 'Nn':
        s = input('Undo last update? [Y/N] ')
        if s in 'Yy':
            undo()
            print("Done!")

